### ISSUE TITLE
データの更新

### ISSUE THREAD

**Issue by takasshii** [takasshii/flutter_test_quiz_app#10]
1. 問題学習後、review画面に値が反映されない
2. 学習した日数がおかしい

**Comment by takasshii** [comment]
review画面のエラー

Unhandled Exception: type 'int' is not a subtype of type 'String?' in type cast
#0      QueryRow.[] (package:sqflite_common/src/collection_utils.dart:134:27)
#1      ReviewModel.fetchQuestionDataList.<anonymous closure> (package:flutter_test_takashii/screens/review/model/review_model.dart:31:37)
#2      ListMixin.forEach (dart:collection/list.dart:86:13)
#3      ReviewModel.fetchQuestionDataList (package:flutter_test_takashii/screens/review/model/review_model.dart:30:18)

**Comment by takasshii** [comment]
↑はforEachで存在しない場所にアクセスしてたことのエラー、解決

**Comment by takasshii** [comment]
1. は解決。2. では今後問題ごとにupdateが来るようにしたい。
